# Generated by Django 3.2.13 on 2022-10-01 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=src.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=src.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('is_registered_user', models.BooleanField(default=True)),
                ('car_type', models.CharField(choices=[('four_seat', 'four_seat'), ('seven_seat', 'seven_seat'), ('any', 'any')], max_length=25)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[('on_app', 'on_app'), ('by_phone', 'by_phone')], default='on_app', max_length=20)),
                ('departure', models.CharField(max_length=512)),
                ('destination', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('wait_for_confirmed', 'wait_for_confirmed'), ('wait_for_driver', 'wait_for_driver'), ('on_going', 'on_going'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='wait_for_confirmed', max_length=30)),
                ('total_distance', models.FloatField()),
                ('total_fee', models.FloatField()),
                ('cancel_count', models.PositiveIntegerField(default=0)),
                ('gps_data', models.JSONField(blank=True, default=list, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_booked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
