# Generated by Django 3.2.13 on 2022-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20221011_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allow_driver_distance',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
