# Generated by Django 3.2.13 on 2022-11-14 16:39

from django.db import migrations
import src.booking.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_driverconfirmbooking_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=src.booking.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None),
        ),
    ]
