# Generated by Django 3.2.13 on 2022-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverconfirmbooking',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
