version: '2'

services:
  # nginx:
    # image: nginx:stable-alpine
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./nginx/error.log:/etc/nginx/error_log.log
    #   - ./nginx/log/:/var/log/nginx
    #   #- ./nginx/cache/:/etc/nginx/cache
    #   #- /etc/letsencrypt/:/etc/letsencrypt/
    #   - ./nginx/sites:/etc/nginx/sites
    #   - ./:/var/www/src
    #   - ./static:/var/www/src/static
    #   # - ./media:/var/www/src/media
    #   # - ./nginx/conf/gzip.conf:/etc/nginx/conf/gzip.conf
    #   # - ./nginx/conf/ssl.conf:/etc/nginx/conf/ssl.conf
    #   # - ./nginx/ssl/:/etc/nginx/ssl
    #   # - ./certbot/certs/:/var/certs
    #   # - ./certbot/letsencrypt/:/var/www/letsencrypt
    # ports:
    #   - 80:80
    #   - 443:443
    # networks:
    #   - nginx_network

  db:
    image: library/postgres:13-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/app/src:Z
      - ./templates/:/app/templates:Z
      # prevents overshadowing of build-time assets
      - /app/src/static/assets
      # shared volume between celery and web for media
      - ./static:/app/static
      - ./media:/app/media
      # - ./nginx/ssl/:/etc/nginx/ssl
      # - ./certbot/certs/:/var/certs
      # - ./certbot/letsencrypt/:/var/www/letsencrypt
    networks:
      - default
      - nginx_network
    env_file: common.debug.env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 8880:80
    networks:
      - default
    volumes:
      - ./pgadmin/servers.json:/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
  
  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A src --app=src.celeryconf:app worker -B --loglevel=info
    restart: unless-stopped
    networks:
      - default
      - nginx_network
    env_file: common.debug.env
    depends_on:
      - redis
      - broker
    volumes:
      - ./src/:/app/src:Z
      - ./templates/:/app/templates:Z,cached
      # shared volume between worker and api for media
      # - ./media:/app/media
  
  redis:
    image: library/redis:6.0-alpine
    restart: unless-stopped
    networks:
      - default
      - nginx_network
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  broker:
    image: library/redis:6.0-alpine
    restart: unless-stopped
    networks:
      - default
      - nginx_network

  broker-rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - default
      - nginx_network

networks:
  default:
    driver: bridge
  nginx_network:
    driver: bridge
