# Generated by Django 3.2.13 on 2022-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('driver', 'driver'), ('call_center', 'call_center'), ('admin', 'admin')], default='customer', max_length=25),
        ),
    ]
